language: rust

rust:
  # "The Rust team appreciates testing against the beta and
  # nightly channels, even if you are only targeting stable."
  - stable
  - nightly

os:
  - linux
  - windows
  - osx

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  global:
    - "TFB_HOME=~/.tfb"
    - "RUST_BACKTRACE=full"

script:
  # TODO: Make sure this points to the real FrameworkBenchmarks repo when ready
  - mkdir ~/.tfb
  - git clone git@github.com:TechEmpower/MockFrameworkBenchmarks.git ~/.tfb
  - cargo test -- --nocapture
